// Textos de la interfaz en español (la referencia) e inglés. Añadir una clave aquí obliga a traducirla:
// EN tiene el mismo tipo que ES. Los {marcadores} se sustituyen en I18n.t().

export const ES = {
  // Navegación
  'nav.equipo': 'Equipo',
  'nav.comparar': 'Comparar',
  'nav.ranking': 'Ranking',
  'nav.duende': 'Duende',
  'nav.buscar': 'Buscar jugador o nick…',
  'nav.sinResultados': 'Nadie con ese nombre',
  'nav.temaClaro': 'Cambiar a modo claro',
  'nav.temaOscuro': 'Cambiar a modo oscuro',
  'nav.idioma': 'Idioma',
  'nav.inicio': 'TTCL Games, inicio',

  // Títulos de pestaña
  'titulo.equipo': 'Equipo',
  'titulo.comparar': 'Comparar',
  'titulo.ranking': 'Ranking',
  'titulo.noEncontrada': 'Página no encontrada',

  // Comunes
  'comun.todos': 'Todos',
  'comun.demo': 'demo',
  'comun.partidas': 'partidas',
  'comun.winrate': 'winrate',
  'comun.ultima': 'última: {fecha}',
  'comun.sincronizado': 'Sincronizado {hace}',
  'comun.sinSync': 'Sin sincronizar todavía',
  'comun.datosEjemplo': 'Datos de ejemplo',
  'comun.errorApi': 'No se puede conectar con la API. ¿Está arrancada en el puerto 8080?',
  'comun.reintentar': 'Reintentar',
  'comun.verTodas': 'Ver todas',
  'comun.cargarMas': 'Cargar más',
  'comun.victoria': 'Victoria',
  'comun.derrota': 'Derrota',
  'comun.sinResultado': 'Sin resultado',
  'comun.formaV': 'V',
  'comun.formaD': 'D',
  'comun.solo': 'solo',
  'comun.juegosDisponibles': 'Juegos disponibles: {juegos}.',
  'comun.pie': 'TTCL Games · estadísticas del equipo',
  'comun.fuentes': 'Datos: FACEIT (CS2) y Hi-Rez (SMITE 2)',

  // Equipo
  'equipo.titulo': 'Equipo TTCL',
  'equipo.sub': 'Estadísticas de las partidas guardadas, actualizadas por el worker de sincronización.',
  'equipo.comparar': 'Comparar dos jugadores →',
  'equipo.vacio':
    'Aún no hay nadie en el equipo. Copia config/equipo.example.json a config/equipo.json o arranca la API con datos de ejemplo.',
  'equipo.vacioJuego': 'Nadie del equipo tiene partidas de {juego}.',
  'equipo.duende': 'El Duende · {juego}',
  'equipo.grupos': 'Los que mejor se entienden',
  'equipo.gruposSub': 'Mejor winrate jugando juntos en el mismo bando',
  'equipo.duo': 'Dúo',
  'equipo.trio': 'Trío',
  'equipo.juntos': '{victorias} de {partidas} juntos',

  // Jugador
  'jugador.volver': '← Equipo',
  'jugador.comparar': 'Comparar',
  'jugador.preguntar': 'Preguntar al Duende',
  'jugador.tabResumen': 'Resumen',
  'jugador.tabPartidas': 'Partidas',
  'jugador.tabMapas': 'Mapas',
  'jugador.tabDioses': 'Dioses',
  'jugador.sinPartidas': '{nombre} aún no tiene partidas guardadas.',
  'jugador.noExiste': 'No hay ningún jugador con ese enlace.',
  'jugador.delta': 'últ. {n}: {delta}',
  'jugador.forma': 'Forma',
  'jugador.ultimas': 'Últimas {n} partidas',
  'jugador.grafica': 'Rendimiento por partida',
  'jugador.kills': 'Kills',
  'jugador.muertes': 'Muertes',
  'jugador.asistencias': 'Asistencias',
  'jugador.porMapa': 'Por mapa',
  'jugador.porDios': 'Por dios',
  'jugador.mejor': 'mejor',
  'jugador.peor': 'peor',
  'jugador.recientes': 'Partidas recientes',
  'jugador.historial': 'Historial · {total} partidas',
  'jugador.pocasParaGrafica': 'Hacen falta al menos 2 partidas para dibujar la gráfica.',
  'jugador.rol': 'Rol en {juego}',
  'jugador.conQuien': 'Con quién',
  'jugador.conQuienSub': 'Tu winrate con cada compañero del equipo y en el resto de partidas',
  'jugador.conQuienVacio': 'Aún no hay partidas suficientes con nadie del equipo.',
  'jugador.solo': 'Solo',
  'jugador.sinEl': 'sin: {winrate}',
  'jugador.conEquipo': 'con el equipo: {winrate}',
  'jugador.cuando': 'Cuándo juegas mejor',
  'jugador.cuandoSub': '{sesiones} sesiones · {media} partidas de media',
  'jugador.cuandoNota':
    'Una sesión son partidas con menos de 45 minutos entre una y otra. Con menos de 15, el Duende aún no saca conclusiones.',
  'jugador.enLaSesion': 'Partida de la sesión',
  'jugador.trasLaAnterior': 'Según la anterior',
  'jugador.horaDelDia': 'Hora del día',
  'jugador.resto': 'resto: {winrate}',

  // Tablas
  'tabla.resultado': 'Resultado',
  'tabla.mapa': 'Mapa',
  'tabla.dios': 'Dios',
  'tabla.marcador': 'Marcador',
  'tabla.cola': 'Cola',
  'tabla.kda': 'K / D / A',
  'tabla.fecha': 'Fecha',
  'tabla.con': 'Con',
  'tabla.jugador': 'Jugador',
  'tabla.partidas': 'Partidas',
  'tabla.juego': 'Juego',

  // Duende
  'duende.nombre': 'El Duende',
  'duende.panelSub': 'En qué mejorar según tus números',
  'duende.nivelAlto': 'Mejorar ya',
  'duende.nivelMedio': 'A vigilar',
  'duende.nivelBien': 'Lo haces bien',
  'duende.nivelInfo': 'Ojo',
  'duende.consejo': 'Consejo:',
  'duende.nadaQueDecir': 'Nada destacable: vas en la media del equipo y de la referencia.',
  'duende.noDisponible':
    'El Duende está echándose la siesta (el servicio Python no responde). Los números siguen aquí.',
  'duende.placeholder': 'Pregúntale algo al Duende…',
  'duende.enviar': 'Enviar',
  'duende.fab': 'Pregunta al Duende',
  'duende.cerrar': 'Cerrar',
  'duende.reiniciar': 'Nueva conversación',
  'duende.ctxEquipo': 'Hablando de todo el equipo',
  'duende.ctxJugador': 'Hablando de {nombre}',
  'duende.ctxComparar': '{a} contra {b}',
  'duende.saludoEquipo':
    '¡Buenas! Soy el Duende. Miro los números de todo el equipo y os digo en qué mejorar. Pregunta lo que quieras.',
  'duende.saludoJugador':
    '¡Buenas! Tengo delante los números de {nombre}. Pregúntame en qué mejorar, qué hace bien o cómo va últimamente.',
  'duende.saludoComparar': 'Tengo a {a} y a {b} frente a frente. ¿Quién quieres que salga peor parado?',
  'duende.pensando': 'El Duende está pensando',
  'duende.error': 'No he podido responder: {error}',
  'duende.errorRed': 'el servicio no responde. Prueba otra vez en un rato.',
  'duende.origenGemini': 'Gemini · {modelo}',
  'duende.origenReglas': 'Sin IA · con reglas',
  'duende.sugMejorar': '¿En qué tengo que mejorar?',
  'duende.sugBien': '¿Qué hago bien?',
  'duende.sugRacha': '¿Cómo voy últimamente?',
  'duende.sugMejorEquipo': '¿Quién es el mejor del equipo?',
  'duende.sugCadaUno': '¿En qué tiene que mejorar cada uno?',
  'duende.sugConQuien': '¿Con quién juego mejor?',
  'duende.sugMejorDuo': '¿Cuál es nuestro mejor dúo?',
  'duende.sugCuando': '¿Cuándo juego mejor?',

  // Comparar
  'comparar.titulo': 'Comparar',
  'comparar.sub': 'Dos jugadores del equipo, cara a cara, métrica a métrica.',
  'comparar.jugadorA': 'Jugador A',
  'comparar.jugadorB': 'Jugador B',
  'comparar.intercambiar': 'Intercambiar jugadores',
  'comparar.juego': 'Juego',
  'comparar.metricas': 'métricas',
  'comparar.sinDatos': '{nombre} no tiene partidas de {juego}.',
  'comparar.mismo': 'Elige dos jugadores distintos.',
  'comparar.faltan': 'Hacen falta al menos dos jugadores en el equipo.',
  'comparar.pocas': 'Ojo: con menos de 5 partidas, las diferencias pueden ser casualidad.',
  'comparar.veredicto': '{lider} va por delante en {n} de {total} métricas.',
  'comparar.empate': 'Empate técnico: {n} métricas cada uno.',
  'comparar.duendeT': '¿Qué opina el Duende?',
  'comparar.duendeSub': 'Pregúntale y te lo dice con datos (y sin piedad).',
  'comparar.preguntaQuien': '¿Quién es mejor?',
  'comparar.preguntaMejorar': '¿En qué tiene que mejorar {nombre}?',

  // Ranking
  'ranking.titulo': 'Ranking',
  'ranking.sub': 'El equipo ordenado por la métrica que elijas. Pulsa una columna para ordenar.',
  'ranking.vacio': 'Nadie del equipo tiene partidas de {juego}.',
  'ranking.ordenar': 'Ordenar por {metrica}',

  // 404
  'noEncontrada.titulo': 'Por aquí no hay nada',
  'noEncontrada.texto': 'La página que buscas no existe o se ha movido.',
  'noEncontrada.volver': 'Volver al equipo',

  // Métricas
  'metrica.partidas': 'Partidas',
  'metrica.winrate': 'Winrate',
  'metrica.kd': 'K/D',
  'metrica.kills_media': 'Kills / partida',
  'metrica.muertes_media': 'Muertes / partida',
  'metrica.asistencias_media': 'Asistencias / partida',
  'metrica.adr': 'ADR',
  'metrica.hs_pct': '% HS',
  'metrica.kr': 'K/R',
  'metrica.entry_pct': 'Éxito de entrada',
  'metrica.clutch_pct': 'Clutches ganados',
  'metrica.mvps': 'MVPs / partida',
  'metrica.multikills': 'Multikills / partida',
  'metrica.dano_utilidad': 'Daño de utilidad',
  'metrica.kda': 'KDA',
  'metrica.dano_min': 'Daño / min',
  'metrica.oro_min': 'Oro / min',
  'metrica.dano': 'Daño / partida',
  'metrica.mitigado': 'Mitigado / partida',
  'metrica.curacion': 'Curación / partida',

  // Roles (los mismos que acepta la API en config/equipo.json)
  'rol.entry': 'Entry',
  'rol.awp': 'AWP',
  'rol.soporte': 'Soporte',
  'rol.lurker': 'Lurker',
  'rol.igl': 'IGL',
  'rol.rifler': 'Rifler',
  'rol.solo': 'Solo',
  'rol.jungla': 'Jungla',
  'rol.mid': 'Mid',
  'rol.guardian': 'Guardián',
  'rol.carry': 'Carry',

  // Periodo (?periodo=7d|30d en la URL)
  'periodo.etiqueta': 'Periodo',
  'periodo.7d': '7 días',
  'periodo.30d': '30 días',
  'periodo.todo': 'Todo',
  'periodo.en.7d': 'en los últimos 7 días',
  'periodo.en.30d': 'en los últimos 30 días',
  'periodo.sinPartidas': '{nombre} no ha jugado a {juego} {periodo}.',
  'periodo.nadie': 'Nadie del equipo ha jugado a {juego} {periodo}.',

  // Filas de las sesiones (las claves que manda la API)
  'momento.1': '1ª',
  'momento.2': '2ª',
  'momento.3+': '3ª en adelante',
  'momento.victoria': 'Tras ganar',
  'momento.derrota': 'Tras perder',
  'momento.manana': 'Mañana (6–14 h)',
  'momento.tarde': 'Tarde (14–20 h)',
  'momento.noche': 'Noche (20–24 h)',
  'momento.madrugada': 'Madrugada (0–6 h)',
} as const;

export type Clave = keyof typeof ES;

export const EN: Record<Clave, string> = {
  'nav.equipo': 'Team',
  'nav.comparar': 'Compare',
  'nav.ranking': 'Leaderboard',
  'nav.duende': 'Duende',
  'nav.buscar': 'Search player or nick…',
  'nav.sinResultados': 'Nobody by that name',
  'nav.temaClaro': 'Switch to light mode',
  'nav.temaOscuro': 'Switch to dark mode',
  'nav.idioma': 'Language',
  'nav.inicio': 'TTCL Games, home',

  'titulo.equipo': 'Team',
  'titulo.comparar': 'Compare',
  'titulo.ranking': 'Leaderboard',
  'titulo.noEncontrada': 'Page not found',

  'comun.todos': 'All',
  'comun.demo': 'demo',
  'comun.partidas': 'matches',
  'comun.winrate': 'win rate',
  'comun.ultima': 'last: {fecha}',
  'comun.sincronizado': 'Synced {hace}',
  'comun.sinSync': 'Not synced yet',
  'comun.datosEjemplo': 'Sample data',
  'comun.errorApi': "Can't reach the API. Is it running on port 8080?",
  'comun.reintentar': 'Retry',
  'comun.verTodas': 'See all',
  'comun.cargarMas': 'Load more',
  'comun.victoria': 'Win',
  'comun.derrota': 'Loss',
  'comun.sinResultado': 'No result',
  'comun.formaV': 'W',
  'comun.formaD': 'L',
  'comun.solo': 'solo',
  'comun.juegosDisponibles': 'Available games: {juegos}.',
  'comun.pie': 'TTCL Games · team stats',
  'comun.fuentes': 'Data: FACEIT (CS2) and Hi-Rez (SMITE 2)',

  'equipo.titulo': 'TTCL Team',
  'equipo.sub': 'Stats from saved matches, kept up to date by the sync worker.',
  'equipo.comparar': 'Compare two players →',
  'equipo.vacio':
    'No one on the team yet. Copy config/equipo.example.json to config/equipo.json or start the API with sample data.',
  'equipo.vacioJuego': 'Nobody on the team has {juego} matches.',
  'equipo.duende': 'The Duende · {juego}',
  'equipo.grupos': 'Best partnerships',
  'equipo.gruposSub': 'Highest win rate playing together on the same side',
  'equipo.duo': 'Duo',
  'equipo.trio': 'Trio',
  'equipo.juntos': '{victorias} of {partidas} together',

  'jugador.volver': '← Team',
  'jugador.comparar': 'Compare',
  'jugador.preguntar': 'Ask the Duende',
  'jugador.tabResumen': 'Overview',
  'jugador.tabPartidas': 'Matches',
  'jugador.tabMapas': 'Maps',
  'jugador.tabDioses': 'Gods',
  'jugador.sinPartidas': '{nombre} has no saved matches yet.',
  'jugador.noExiste': 'There is no player at this link.',
  'jugador.delta': 'last {n}: {delta}',
  'jugador.forma': 'Form',
  'jugador.ultimas': 'Last {n} matches',
  'jugador.grafica': 'Performance per match',
  'jugador.kills': 'Kills',
  'jugador.muertes': 'Deaths',
  'jugador.asistencias': 'Assists',
  'jugador.porMapa': 'By map',
  'jugador.porDios': 'By god',
  'jugador.mejor': 'best',
  'jugador.peor': 'worst',
  'jugador.recientes': 'Recent matches',
  'jugador.historial': 'History · {total} matches',
  'jugador.pocasParaGrafica': 'At least 2 matches are needed to draw the chart.',
  'jugador.rol': 'Role in {juego}',
  'jugador.conQuien': 'Who with',
  'jugador.conQuienSub': 'Your win rate with each teammate and in the rest of your matches',
  'jugador.conQuienVacio': 'Not enough matches with anyone on the team yet.',
  'jugador.solo': 'Solo',
  'jugador.sinEl': 'without: {winrate}',
  'jugador.conEquipo': 'with the team: {winrate}',
  'jugador.cuando': 'When you play best',
  'jugador.cuandoSub': '{sesiones} sessions · {media} matches on average',
  'jugador.cuandoNota':
    'A session is matches less than 45 minutes apart. With fewer than 15, the Duende draws no conclusions yet.',
  'jugador.enLaSesion': 'Match in the session',
  'jugador.trasLaAnterior': 'After the previous one',
  'jugador.horaDelDia': 'Time of day',
  'jugador.resto': 'rest: {winrate}',

  'tabla.resultado': 'Result',
  'tabla.mapa': 'Map',
  'tabla.dios': 'God',
  'tabla.marcador': 'Score',
  'tabla.cola': 'Queue',
  'tabla.kda': 'K / D / A',
  'tabla.fecha': 'Date',
  'tabla.con': 'With',
  'tabla.jugador': 'Player',
  'tabla.partidas': 'Matches',
  'tabla.juego': 'Game',

  'duende.nombre': 'The Duende',
  'duende.panelSub': 'What to improve, by the numbers',
  'duende.nivelAlto': 'Fix now',
  'duende.nivelMedio': 'Keep an eye on',
  'duende.nivelBien': 'Doing well',
  'duende.nivelInfo': 'Heads up',
  'duende.consejo': 'Tip:',
  'duende.nadaQueDecir': "Nothing stands out: you're on the team average and the benchmark.",
  'duende.noDisponible': "The Duende is taking a nap (the Python service isn't answering). The numbers are still here.",
  'duende.placeholder': 'Ask the Duende something…',
  'duende.enviar': 'Send',
  'duende.fab': 'Ask the Duende',
  'duende.cerrar': 'Close',
  'duende.reiniciar': 'New conversation',
  'duende.ctxEquipo': 'Talking about the whole team',
  'duende.ctxJugador': 'Talking about {nombre}',
  'duende.ctxComparar': '{a} versus {b}',
  'duende.saludoEquipo': "Hey! I'm the Duende. I look at the whole team's numbers and tell you what to improve. Ask away.",
  'duende.saludoJugador':
    "Hey! I've got {nombre}'s numbers in front of me. Ask me what to improve, what they do well or how they've been doing lately.",
  'duende.saludoComparar': "I've got {a} and {b} face to face. Who do you want to come off worse?",
  'duende.pensando': 'The Duende is thinking',
  'duende.error': "I couldn't answer: {error}",
  'duende.errorRed': "the service isn't answering. Try again in a while.",
  'duende.origenGemini': 'Gemini · {modelo}',
  'duende.origenReglas': 'No AI · rule-based',
  'duende.sugMejorar': 'What should I improve?',
  'duende.sugBien': 'What am I good at?',
  'duende.sugRacha': 'How have I been doing lately?',
  'duende.sugMejorEquipo': "Who's the best on the team?",
  'duende.sugCadaUno': 'What should each of us improve?',
  'duende.sugConQuien': 'Who do I play best with?',
  'duende.sugMejorDuo': "What's our best duo?",
  'duende.sugCuando': 'When do I play best?',

  'comparar.titulo': 'Compare',
  'comparar.sub': 'Two teammates, face to face, metric by metric.',
  'comparar.jugadorA': 'Player A',
  'comparar.jugadorB': 'Player B',
  'comparar.intercambiar': 'Swap players',
  'comparar.juego': 'Game',
  'comparar.metricas': 'metrics',
  'comparar.sinDatos': '{nombre} has no {juego} matches.',
  'comparar.mismo': 'Pick two different players.',
  'comparar.faltan': 'You need at least two players on the team.',
  'comparar.pocas': 'Careful: with fewer than 5 matches, differences may be luck.',
  'comparar.veredicto': '{lider} leads in {n} of {total} metrics.',
  'comparar.empate': 'Dead even: {n} metrics each.',
  'comparar.duendeT': 'What does the Duende think?',
  'comparar.duendeSub': "Ask and you'll get it with data (and no mercy).",
  'comparar.preguntaQuien': "Who's better?",
  'comparar.preguntaMejorar': 'What should {nombre} improve?',

  'ranking.titulo': 'Leaderboard',
  'ranking.sub': 'The team sorted by the metric you pick. Click a column to sort.',
  'ranking.vacio': 'Nobody on the team has {juego} matches.',
  'ranking.ordenar': 'Sort by {metrica}',

  'noEncontrada.titulo': 'Nothing here',
  'noEncontrada.texto': "The page you're looking for doesn't exist or has moved.",
  'noEncontrada.volver': 'Back to the team',

  'metrica.partidas': 'Matches',
  'metrica.winrate': 'Win rate',
  'metrica.kd': 'K/D',
  'metrica.kills_media': 'Kills / match',
  'metrica.muertes_media': 'Deaths / match',
  'metrica.asistencias_media': 'Assists / match',
  'metrica.adr': 'ADR',
  'metrica.hs_pct': 'HS %',
  'metrica.kr': 'K/R',
  'metrica.entry_pct': 'Entry success',
  'metrica.clutch_pct': 'Clutches won',
  'metrica.mvps': 'MVPs / match',
  'metrica.multikills': 'Multi-kills / match',
  'metrica.dano_utilidad': 'Utility damage',
  'metrica.kda': 'KDA',
  'metrica.dano_min': 'Damage / min',
  'metrica.oro_min': 'Gold / min',
  'metrica.dano': 'Damage / match',
  'metrica.mitigado': 'Mitigated / match',
  'metrica.curacion': 'Healing / match',

  'rol.entry': 'Entry',
  'rol.awp': 'AWP',
  'rol.soporte': 'Support',
  'rol.lurker': 'Lurker',
  'rol.igl': 'IGL',
  'rol.rifler': 'Rifler',
  'rol.solo': 'Solo',
  'rol.jungla': 'Jungle',
  'rol.mid': 'Mid',
  'rol.guardian': 'Guardian',
  'rol.carry': 'Carry',

  'periodo.etiqueta': 'Period',
  'periodo.7d': '7 days',
  'periodo.30d': '30 days',
  'periodo.todo': 'All',
  'periodo.en.7d': 'in the last 7 days',
  'periodo.en.30d': 'in the last 30 days',
  'periodo.sinPartidas': "{nombre} hasn't played {juego} {periodo}.",
  'periodo.nadie': 'Nobody on the team has played {juego} {periodo}.',

  'momento.1': '1st',
  'momento.2': '2nd',
  'momento.3+': '3rd onwards',
  'momento.victoria': 'After a win',
  'momento.derrota': 'After a loss',
  'momento.manana': 'Morning (6–14 h)',
  'momento.tarde': 'Afternoon (14–20 h)',
  'momento.noche': 'Evening (20–24 h)',
  'momento.madrugada': 'Late night (0–6 h)',
};
