-- Esquema inicial. SQL compatible con PostgreSQL y con H2 en modo PostgreSQL (desarrollo y tests).

-- Un miembro del equipo.
CREATE TABLE jugadores (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(50)  NOT NULL UNIQUE,
    nombre     VARCHAR(100) NOT NULL,
    demo       BOOLEAN      NOT NULL DEFAULT FALSE,
    creado_en  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Cuenta de un jugador en un juego. external_id es null hasta que el worker la resuelve por el nick.
CREATE TABLE cuentas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jugador_id      BIGINT       NOT NULL REFERENCES jugadores (id) ON DELETE CASCADE,
    juego           VARCHAR(20)  NOT NULL,
    external_id     VARCHAR(100),
    nombre_externo  VARCHAR(100) NOT NULL,
    ultima_sync     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT cuentas_juego_external_uq UNIQUE (juego, external_id),
    CONSTRAINT cuentas_jugador_juego_uq UNIQUE (jugador_id, juego)
);

-- Partida compartida: una fila aunque la jugaran varios del equipo.
CREATE TABLE partidas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    juego         VARCHAR(20)  NOT NULL,
    external_id   VARCHAR(100) NOT NULL,
    jugada_en     TIMESTAMP WITH TIME ZONE NOT NULL,
    duracion_seg  INTEGER,
    modo          VARCHAR(100),
    CONSTRAINT partidas_juego_external_uq UNIQUE (juego, external_id)
);
CREATE INDEX partidas_fecha_idx ON partidas (jugada_en);

-- Lo que hizo cada jugador del equipo en una partida. Lo específico de cada juego va en datos (JSON).
CREATE TABLE participaciones (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partida_id   BIGINT      NOT NULL REFERENCES partidas (id) ON DELETE CASCADE,
    jugador_id   BIGINT      NOT NULL REFERENCES jugadores (id) ON DELETE CASCADE,
    juego        VARCHAR(20) NOT NULL,
    gano         BOOLEAN,
    kills        INTEGER,
    muertes      INTEGER,
    asistencias  INTEGER,
    datos        VARCHAR(4000) NOT NULL DEFAULT '{}',
    CONSTRAINT participaciones_partida_jugador_uq UNIQUE (partida_id, jugador_id)
);
CREATE INDEX participaciones_jugador_juego_idx ON participaciones (jugador_id, juego);

-- Historial de sincronizaciones.
CREATE TABLE syncs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id        BIGINT      NOT NULL REFERENCES cuentas (id) ON DELETE CASCADE,
    empezada_en      TIMESTAMP WITH TIME ZONE NOT NULL,
    terminada_en     TIMESTAMP WITH TIME ZONE,
    estado           VARCHAR(10) NOT NULL,
    partidas_nuevas  INTEGER     NOT NULL DEFAULT 0,
    error            VARCHAR(500)
);
CREATE INDEX syncs_cuenta_idx ON syncs (cuenta_id, empezada_en);
