-- P6: memoria de consejos. Lo que el Duende le ha dicho a cada uno (los avisos de mejorar ya y a vigilar), con el
-- valor que tenía la métrica ese día, para ver después si el consejo ha funcionado.
CREATE TABLE consejos_dados (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jugador_id  BIGINT       NOT NULL REFERENCES jugadores (id) ON DELETE CASCADE,
    juego       VARCHAR(20)  NOT NULL,
    -- Id de la recomendación del Duende (debil_adr, kd_sin_victorias, tilt_sesion...).
    insight     VARCHAR(60)  NOT NULL,
    -- Métrica de la que habla (adr, winrate...) y su valor con todas las partidas ese día; null si no habla de una.
    metrica     VARCHAR(40),
    valor       DOUBLE PRECISION,
    nivel       VARCHAR(10)  NOT NULL,
    dado_en     TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX consejos_dados_jugador_idx ON consejos_dados (jugador_id, juego, dado_en);
