-- P7: valoración de las respuestas. Los votos de la web (me sirve / no me sirve) a las recomendaciones del Duende y a
-- sus respuestas del chat, con lo que se vio, para revisar las peor valoradas y cambiar las reglas o el prompt.
CREATE TABLE valoraciones (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- "consejo" (una recomendación del panel) o "respuesta" (una respuesta del chat).
    tipo        VARCHAR(10)   NOT NULL,
    -- Lo que se valora: el id de la recomendación (debil_adr, tilt_sesion...) o el hash de la pregunta y la respuesta.
    clave       VARCHAR(64)   NOT NULL,
    -- 1 (me sirve) o -1 (no me sirve).
    voto        INTEGER       NOT NULL,
    -- Quién la escribió: "reglas" o "gemini", con su modelo. Las recomendaciones son siempre de reglas.
    origen      VARCHAR(10)   NOT NULL,
    modelo      VARCHAR(80),
    -- Solo en el chat: de qué iba la pregunta según las reglas (mejorar, companeros... o ayuda si no la entienden).
    intencion   VARCHAR(30),
    -- Solo en las recomendaciones: alto, medio, bien o info.
    nivel       VARCHAR(10),
    -- De quién y de qué juego se hablaba. En el chat, el primero del foco (null si iba del equipo entero).
    jugador_id  BIGINT        REFERENCES jugadores (id) ON DELETE CASCADE,
    juego       VARCHAR(20),
    lang        VARCHAR(2)    NOT NULL,
    -- Lo que se vio, para leerlo al revisar: la pregunta (solo en el chat) y la respuesta o la recomendación.
    pregunta    VARCHAR(2000),
    texto       VARCHAR(8000) NOT NULL,
    -- Un id al azar de cada navegador, sin datos personales: un voto por persona y cosa valorada, que se puede cambiar.
    votante     VARCHAR(40)   NOT NULL,
    votada_en   TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX valoraciones_votante_idx ON valoraciones (votante, tipo, clave);
