-- P8: comparar con jugadores de tu nivel. Nivel y ELO de FACEIT de cada cuenta (null en SMITE 2 o sin sincronizar).
ALTER TABLE cuentas ADD COLUMN nivel INTEGER;
ALTER TABLE cuentas ADD COLUMN elo INTEGER;

-- Lo que hizo cada jugador que no es del equipo en las partidas sincronizadas, con su nivel en esa partida. Sin nick
-- ni id (ni del jugador ni de la partida): solo sirve para saber qué es lo normal en cada nivel.
CREATE TABLE muestras (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    juego        VARCHAR(20)  NOT NULL,
    nivel        INTEGER      NOT NULL,
    mapa         VARCHAR(100),
    -- Día de la partida, para poder descartar las muestras viejas.
    fecha        DATE         NOT NULL,
    gano         BOOLEAN,
    kills        INTEGER,
    muertes      INTEGER,
    asistencias  INTEGER,
    -- Lo específico del juego, como en participaciones (adr, hs_pct, kr, entradas, clutches, utilidad...).
    datos        VARCHAR(4000) NOT NULL DEFAULT '{}'
);
CREATE INDEX muestras_juego_nivel_idx ON muestras (juego, nivel);
