-- P12: análisis de demos de CS2. El trabajador de análisis (analisis/) lee la demo de cada partida y la API guarda lo
-- que hizo cada jugador del equipo en cada ronda.

-- Steamid de la cuenta de CS2 (lo da FACEIT en el perfil): con él se encuentra a cada uno dentro de la demo.
ALTER TABLE cuentas ADD COLUMN steam_id VARCHAR(20);

-- La demo de cada partida de CS2 y en qué punto está su análisis.
CREATE TABLE demos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partida_id      BIGINT        NOT NULL UNIQUE REFERENCES partidas (id) ON DELETE CASCADE,
    -- La URL de la demo en FACEIT (sin firmar), si la dio. Sin ella, se busca en la carpeta de demos por el id de la
    -- partida.
    url             VARCHAR(500),
    -- pendiente, analizada o fallida (la demo no vale, ha caducado o no se ha podido leer).
    estado          VARCHAR(10)   NOT NULL,
    intentos        INTEGER       NOT NULL DEFAULT 0,
    error           VARCHAR(500),
    -- Cuándo se miró por última vez: se van mirando por turnos, la que hace más que no se mira primero.
    revisada_en     TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX demos_estado_idx ON demos (estado, revisada_en);

-- Las partidas de CS2 que ya estaban: pendientes, por si aparece su demo en la carpeta.
INSERT INTO demos (partida_id, estado, intentos, revisada_en)
SELECT id, 'pendiente', 0, CURRENT_TIMESTAMP FROM partidas WHERE juego = 'cs2';

-- Lo que hizo cada jugador del equipo en cada ronda de las partidas analizadas.
CREATE TABLE rondas (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partida_id         BIGINT      NOT NULL REFERENCES partidas (id) ON DELETE CASCADE,
    jugador_id         BIGINT      NOT NULL REFERENCES jugadores (id) ON DELETE CASCADE,
    ronda              INTEGER     NOT NULL,
    -- CT o T.
    lado               VARCHAR(2),
    -- Si su equipo ganó la ronda.
    gano               BOOLEAN,
    kills              INTEGER     NOT NULL DEFAULT 0,
    asistencias        INTEGER     NOT NULL DEFAULT 0,
    asistencias_flash  INTEGER     NOT NULL DEFAULT 0,
    -- Daño a rivales, como mucho 100 por rival; y el de granadas y molotov.
    dano               INTEGER     NOT NULL DEFAULT 0,
    dano_utilidad      INTEGER     NOT NULL DEFAULT 0,
    murio              BOOLEAN     NOT NULL DEFAULT FALSE,
    -- Dónde murió: coordenadas del juego y la zona que da el juego (BombsiteA, TopofMid...).
    muerte_x           DOUBLE PRECISION,
    muerte_y           DOUBLE PRECISION,
    muerte_zona        VARCHAR(40),
    -- Murió y alguien de su lado mató a su asesino en menos de 5 segundos.
    tradeado           BOOLEAN     NOT NULL DEFAULT FALSE,
    -- Kills a rivales que acababan de matar a un compañero.
    trades             INTEGER     NOT NULL DEFAULT 0,
    -- El primer duelo de la ronda: ganada o perdida (null si no fue suyo).
    apertura           VARCHAR(8),
    -- Lo que llevaba encima al empezar la ronda y qué compra era: pistola, eco, forzada o completa.
    equipamiento       INTEGER,
    compra             VARCHAR(10),
    -- Kill, asistencia, sobrevivir o ser tradeado.
    kast               BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT rondas_partida_jugador_ronda_uq UNIQUE (partida_id, jugador_id, ronda)
);
CREATE INDEX rondas_jugador_idx ON rondas (jugador_id);

-- Dónde muere la gente en cada mapa (los diez de cada partida analizada), sin decir quién ni en qué partida: solo sirve
-- para dibujar el mapa debajo del mapa de calor.
CREATE TABLE muertes_mapa (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapa  VARCHAR(100)     NOT NULL,
    x     DOUBLE PRECISION NOT NULL,
    y     DOUBLE PRECISION NOT NULL,
    zona  VARCHAR(40)
);
CREATE INDEX muertes_mapa_idx ON muertes_mapa (mapa);
